name: Java CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Set up repository
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: "gradle"

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build and tests with Gradle
        run: ./gradlew build

      - name: Package JAR file
        run: |
          ./gradlew shadowJar

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/libs/duke.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
